name: Release to Nexus Repository

on:
  pull_request_target:
    branches:    
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Verify
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean verify"
      # Runs a single command using the runners shell
      - name: Done!
        run: echo Done!
