name: Release to Nexus Repository

on:
  pull_request:
    branches:    
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify build
        run: mvn clean verify

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
         GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
         PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        
      - name: Prepare release
        uses: qcastel/github-actions-maven-release@master
        with:
          ssh-private-key: ${{ secrets.OSSRH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.OSSRH_PASSPHRASE }}
          release-branch-name: "release"
          skip-perform: true
          
      # Runs a single command using the runners shell
      - name: Done!
        run: echo Done!
