name: Release to Nexus Repository

on:
  pull_request:
    branches:    
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify build
        run: mvn clean verify
          
      - name: Prepare release
        run: mvn --batch-mode  release:prepare -DtagNameFormat=asset-share-commons-@{project.version} -DreleaseVersion=10.10.10 -DpushChanges=false -DdryRun=true
          
      # Runs a single command using the runners shell
      - name: Done!
        run: echo Done!
