name: Java CI with Maven

on:
  pull_request:
    branches:
      - develop

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          cache: maven
          java-version: ${{ matrix.java }}


      - name: Build & Test with Maven
        run: mvn -U clean verify

      - name: Upload CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
